apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: service-broker-cert
  labels:
    app: enmasse
    component: service-broker
  name: service-broker
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    component: service-broker
  type: ClusterIP
