apiVersion: v1
kind: ClusterRole
metadata:
  name: namespace-admin
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - ''
  - rbac.authorization.k8s.io
  - project.openshift.io
  resources:
  - projectrequests
  - rolebindings
  - roles
  verbs:
  - create
- apiGroups:
  - ''
  - authorization.openshift.io
  resources:
  - namespaces
  - rolebindings
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - patch
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  verbs:
  - create
