- hosts: localhost
  vars:
    namespace: enmasse
    multitenant: true
    enable_rbac: true
    admin_user: developer
    keycloak_admin_password: admin
    authentication_services:
      - standard
      - none
  roles:
    - enmasse
