apiVersion: v1
items:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-address-admin
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - create
    - delete
    - list
    - get
    - watch
    - update
    - patch
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-admin
  rules:
  - apiGroups:
    - ''
    - user.openshift.io
    resources:
    - users
    verbs:
    - impersonate
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: event-reporter
  rules:
  - apiGroups:
    - ''
    resources:
    - events
    verbs:
    - create
    - get
    - update
    - patch
kind: List
