apiVersion: v1
kind: Template
metadata:
  name: enmasse-service-broker
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: service-broker-cert
    labels:
      app: enmasse
      component: service-broker
    name: service-broker
  spec:
    ports:
    - name: https
      port: ${{LISTEN_PORT}}
      protocol: TCP
      targetPort: https
    selector:
      component: service-broker
    type: ClusterIP
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: enmasse
      component: service-broker
    name: service-broker
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: enmasse
          component: service-broker
      spec:
        containers:
        - env:
          - name: ENABLE_RBAC
            value: ${ENABLE_RBAC}
          - name: IMPERSONATE_USER
            value: ${IMPERSONATE_USER}
          - name: KEYCLOAK_CA
            valueFrom:
              secretKeyRef:
                key: tls.crt
                name: ${KEYCLOAK_CA_SECRET}
          - name: KEYCLOAK_ADMIN_USER
            valueFrom:
              secretKeyRef:
                key: admin.username
                name: ${KEYCLOAK_CREDENTIALS_SECRET}
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: admin.password
                name: ${KEYCLOAK_CREDENTIALS_SECRET}
          - name: KEYCLOAK_URL
            valueFrom:
              configMapKeyRef:
                key: httpUrl
                name: ${KEYCLOAK_CONFIG}
          - name: CERT_DIR
            value: /service-broker-cert
          - name: LISTEN_PORT
            value: ${LISTEN_PORT}
          image: ${SERVICE_BROKER_IMAGE}
          livenessProbe:
            httpGet:
              path: /healthz
              ports: https
              scheme: HTTPS
          name: service-broker
          ports:
          - containerPort: ${{LISTEN_PORT}}
            name: https
          volumeMounts:
          - mountPath: /service-broker-cert
            name: service-broker-cert
            readOnly: true
        serviceAccount: ${SERVICE_BROKER_SA}
        volumes:
        - name: service-broker-cert
          secret:
            secretName: service-broker-cert
parameters:
- description: Service broker service account
  name: SERVICE_BROKER_SA
  value: enmasse-admin
- description: Container image to use for service broker
  name: SERVICE_BROKER_IMAGE
  value: docker.io/enmasseproject/service-broker:latest
- description: User to impersonate when creating resources
  name: IMPERSONATE_USER
- description: Secret containing credentials for keycloak
  name: KEYCLOAK_CREDENTIALS_SECRET
  value: keycloak-credentials
- description: Secret containing keycloak certificate
  name: KEYCLOAK_CA_SECRET
  value: standard-authservice-cert
- description: Enable RBAC authentication and authorization of API
  name: ENABLE_RBAC
  value: 'false'
- description: Name of configmap for keycloak configuration
  name: KEYCLOAK_CONFIG
  value: keycloak-config
